# Generated by Django 4.2.27 on 2026-05-09 06:22

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


def copy_existing_artist_contacts(apps, schema_editor):
    Artist = apps.get_model('products', 'Artist')
    ArtistApplication = apps.get_model('products', 'ArtistApplication')

    for artist in Artist.objects.select_related('user').all():
        if artist.user_id and getattr(artist.user, 'email', ''):
            artist.artist_email = artist.user.email
            artist.save(update_fields=['artist_email'])

    for application in ArtistApplication.objects.select_related('user').all():
        update_fields = []
        if application.user_id:
            user = application.user
            if not application.applicant_name:
                full_name = f"{getattr(user, 'first_name', '')} {getattr(user, 'last_name', '')}".strip()
                application.applicant_name = full_name or user.username
                update_fields.append('applicant_name')
            if not application.applicant_email:
                application.applicant_email = user.email
                update_fields.append('applicant_email')
            if not application.applicant_phone and getattr(user, 'phone_number', ''):
                application.applicant_phone = user.phone_number
                update_fields.append('applicant_phone')
        if update_fields:
            application.save(update_fields=update_fields)


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('products', '0013_artistapplication_artist_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='artist',
            name='artist_email',
            field=models.EmailField(blank=True, db_column='ARTIST_EMAIL', max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='artistapplication',
            name='applicant_email',
            field=models.EmailField(blank=True, db_column='APPLICANT_EMAIL', max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='artistapplication',
            name='applicant_name',
            field=models.CharField(blank=True, db_column='APPLICANT_NAME', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='artistapplication',
            name='applicant_phone',
            field=models.CharField(blank=True, db_column='APPLICANT_PHONE', max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='artistapplication',
            name='user',
            field=models.ForeignKey(blank=True, db_column='USER_ID', null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.RunPython(copy_existing_artist_contacts, migrations.RunPython.noop),
        migrations.RemoveField(
            model_name='artist',
            name='user',
        ),
    ]
