# Generated by Django 4.2.27 on 2026-05-09 06:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0014_remove_artist_user_artist_artist_email_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='artistapplication',
            name='artist_brgy',
            field=models.CharField(blank=True, db_column='ARTIST_BRGY', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='artistapplication',
            name='artist_description',
            field=models.TextField(blank=True, db_column='ARTIST_DESCRIPTION', null=True),
        ),
        migrations.AddField(
            model_name='artistapplication',
            name='artist_municipality',
            field=models.CharField(blank=True, db_column='ARTIST_MUNICIPALITY', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='artistapplication',
            name='artist_zipcode',
            field=models.CharField(blank=True, db_column='ARTIST_ZIPCODE', max_length=10, null=True),
        ),
    ]
