# Generated by Django 4.2.27 on 2026-05-15 20:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0015_artistapplication_artist_brgy_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ArtistStockAdjustmentRequest',
        ),
    ]
