# Generated by Django 4.2.27 on 2026-05-17 21:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0016_delete_artiststockadjustmentrequest'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderdetail',
            name='item_status',
            field=models.CharField(db_column='ITEM_STATUS', default='Pending', max_length=50),
        ),
    ]
